[target.nvptx64-nvidia-cuda]
# ref: https://developer.nvidia.com/cuda-gpus
#rustflags = ["-Z", "unstable-options", "-C", "linker-flavor=llbc", "-C", "target-cpu=sm_89", "-Z", "tune-cpu=sm_89"]
rustflags = ["-Z", "unstable-options", "-C", "linker-flavor=llbc"]
