[target.nvptx64-nvidia-cuda]
rustflags = [
    "-Z", "unstable-options",
    "-C", "linker-flavor=llbc",
    "-C", "target-feature=+ptx86",
    "-C", "target-cpu=sm_80",
    "-Z", "tune-cpu=sm_80",
]
